---
driver:
  name: vagrant_remote
  remote_user: mzp
  remote_host: 192.168.11.108

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: sandbox
    driver:
      box: ubuntu/xenial64
    run_list:
      - recipe[git::default]
    attributes:
