version: "2"
services:
  dev:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    command: bash --login
    volumes:
      - .:/kitchen-vagrant-remote
      - ${HOME}/.ssh:/root/.ssh
